name: Build and publish GHPages

on: 
  push:
    branches:
    - main

jobs:
  gradle:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew asciidoctor

      
      - name: Deploy GHpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}      
          publish_branch: gh-pages
          publish_dir: ./build/docs/asciidoc/


